name: generate_zensical

on:
  workflow_run:
    workflows: [ generate_docs,generate_stats,avm_ftp,avm_osp,avm_juis,avm_juis-recache ]
    types:
      - completed
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/generate_zensical.yml'
      - '.github/zensical/*'
      - 'docs/**/*.md'
      - 'docs/**/*.jpg'
      - 'docs/**/*.png'
      - 'docs/**/*.gif'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    env:
      ZENSICAL_REQUIREMENTS_FILE: .github/zensical/requirements.txt
      ZENSICAL_CONFIG_FILE: .github/zensical/zensical.toml
      ZENSICAL_INPUT_PATH: .github/zensical/site
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: pip install -r "${{ env.ZENSICAL_REQUIREMENTS_FILE }}"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Zensical
        run: zensical build --config-file "${{ env.ZENSICAL_CONFIG_FILE }}"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "${{ env.ZENSICAL_INPUT_PATH }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
