name: make_os

on:
# push:
#   branches: [ master ]
#   paths:
#     - '.github/workflows/make_os.yml'
# schedule:
#   - cron: '00 15 * * 6'
  workflow_dispatch:
    inputs:
      os:
        description: "Distro to build"
        required: true
        default: "_all"
        type: choice
        options:
          - "_all"
          - "fedora:43"
          - "debian:13"
          - "ubuntu:22.04"
          - "ubuntu:24.04"
      fos:
        description: "FOS Version to build"
        required: true
        default: "08_0X"
        type: choice
        options:
          - "04_XX"
          - "05_2X"
          - "05_5X"
          - "06_0X"
          - "06_2X"
          - "06_5X"
          - "06_8X"
          - "06_9X"
          - "07_0X"
          - "07_1X"
          - "07_2X"
          - "07_5X"
          - "08_0X"
          - "08_2X"
      box:
        description: "BOX Type to build"
        required: true
        default: "7530_W5"
        type: string
      tools:
        description: "Compile Tools?"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"
      toolchains:
        description: "Compile Toolchains?"
        required: true
        default: "no"
        type: choice
        options:
          - "yes"
          - "no"
      rootemu:
        description: "Use Rootemu?"
        required: true
        default: "pseudo"
        type: choice
        options:
          - "fakeroot"
          - "pseudo"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  dockerfizieren:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.parse.outputs.os }}
    steps:
      - name: list
        id: list
        run: |
          if [ "${{ github.event.inputs.os }}" != "_all" ]; then \
            OSLIST="
            ${{ github.event.inputs.os }}
            "
          else
            OSLIST="
            fedora:43
            debian:13
            ubuntu:22.04
            ubuntu:24.04
            "
          fi
          echo "oslist<<EOF" >> $GITHUB_OUTPUT
          echo "$OSLIST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: parse
        id: parse
        run: |
          OSLIST="${{ steps.list.outputs.oslist }}"
          OSLIST_JSON=$(echo "$OSLIST" | awk 'NF {printf "\"%s\",", $0}' | sed 's/,$//')
          echo "os=[$OSLIST_JSON]" >> $GITHUB_OUTPUT
          echo "################################################################"
          echo "OSLIST_JSON=[$OSLIST_JSON]"

  matrizifizieren:
    if: ${{ github.event.inputs.toolchains != 'no' }}
    permissions:
      contents: read
    container:
#     image: ubuntu:20.04
#     image: freetzng/generate
      image: ghcr.io/freetz-ng/generate
      options: --user 1001:1001
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.parse.outputs.matrix }}

    steps:

      - name: clone
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          set-safe-directory: true
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          path: ${{ github.workspace }}
          fetch-depth: 0
          clean: false
          persist-credentials: true

      - name: parse
        id: parse
        run: |
          sed -rn 's/.* && dltc "(.*)".*/\1/p' tools/dl-toolchains_make | \
          while read -r line; do \
          name="$(echo "$line" | sed -r 's/^FREETZ_TYPE_([^ ]*) *FREETZ_TYPE_FIRMWARE_([^ ]*).*/\1 - \2/g')"; \
          tcs="$(echo "$line" | sed -r 's/^FREETZ_TYPE_([^ ]*) *FREETZ_TYPE_FIRMWARE_([^ ]*)(.*)/_\1 _FIRMWARE_\2\3/g')"; \
          echo -n "$matrix{name:\"$name\",tcs:\"$tcs\"},"; done | \
          sed 's/^/matrix=\[/;s/$/\]/' >> $GITHUB_OUTPUT

      - name: vars
        run: |
          echo "################################################################"
          echo "matrix=${{ steps.parse.outputs.matrix }}" | sed 's/\[{/\[\n{/;s/},{/},\n{/g;s/},\]/},\n\]/'

  build:
    if: ${{ github.event.inputs.toolchains != 'yes' }}
    needs: [ dockerfizieren ]
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        docker: ${{ fromJson(needs.dockerfizieren.outputs.os) }}
    name: "${{ matrix.docker }}"
    runs-on: ubuntu-latest
#   if: github.repository == 'freetz-ng/freetz-ng'

    env:
      CACHE_KEY: "${{ github.workflow }}--${{ matrix.docker }}"
      docker_NAME: "${{ github.job }}"
    steps:

      - name: sleep
        run: |
          SLEEP="$((1 + $(od -A n -t d -N 2 /dev/urandom | tr -d ' ') % 9))"
          echo "Sleeping $SLEEP seconds ..."
          sleep $SLEEP

      - name: myips
        run: |
          echo -n "IP: " ; wget -q https://ipaddress.ai    -O - || echo none
#         echo -n "V4: " ; wget -q https://ipaddress.ai -4 -O - || echo none
#         echo -n "V6: " ; wget -q https://ipaddress.ai -6 -O - || echo none

      - &clone
        name: clone
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          set-safe-directory: true
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
          path: ${{ github.workspace }}
          fetch-depth: 0
          clean: false
          persist-credentials: true

      - name: cache_load
        uses: actions/cache/restore@v4
        if: always()
        with:
          path: |
            dl/*
            !dl/fw/*
          key: ${{ env.CACHE_KEY }}

      - name: config
        run: |
          FOS="${{ github.event.inputs.fos }}"
          BOX="${{ github.event.inputs.box }}"
          COMPILE_TOOLS="${{ github.event.inputs.tools }}"
          USE_ROOTEMU="${{ github.event.inputs.rootemu }}"
          truncate -s0 .config
          echo 'FREETZ_MODULES_OWN=""'                                                                >> .config
          for x in  UDEVMOUNT                               ; do echo "# FREETZ_PATCH_$x is not set"  >> .config; done
          for x in  dummy loop usbserial                   ; do echo "# FREETZ_MODULE_$x is not set"  >> .config; done
          for x in  DROPBEAR                              ; do echo "# FREETZ_PACKAGE_$x is not set"  >> .config; done
          for x in  LDD                                              ; do echo "FREETZ_PACKAGE_$x=y"  >> .config; done
          for x in  COMPRESSED  UNCOMPRESSED                        ; do echo "FREETZ_SIZEINFO_$x=y"  >> .config; done
          echo '# FREETZ_TOOLCHAIN_CCACHE is not set'                                                 >> .config
          echo 'FREETZ_VERBOSITY_FWMOD_2=y'                                                           >> .config
          echo 'FREETZ_VERBOSITY_LEVEL_0=y'                                                           >> .config
          echo 'FREETZ_VERBOSITY_LEVEL=0'                                                             >> .config
          echo 'FREETZ_SERIES_ALL=y'                                                                  >> .config
          echo 'FREETZ_USER_LEVEL_DEVELOPER=y'                                                        >> .config
          echo '# FREETZ_MODULES_TEST in not set'                                                     >> .config
          echo 'FREETZ_DL_SITE_USER="https://raw.githubusercontent.com/Freetz-NG/dl-mirror/master"'   >> .config
          echo 'FREETZ_REAL_DEVELOPER_ONLY__DLIMG="${{ secrets.ACTIONS_IMAGE }}"'                     >> .config
          echo 'FREETZ_REAL_DEVELOPER_ONLY__DLURL="${{ secrets.ACTIONS_DLTCS }}"'                     >> .config
          [[ "$COMPILE_TOOLS" == "yes" ]] && echo '# FREETZ_DOWNLOAD_TOOLCHAIN is not set'            >> .config
          [[ "$COMPILE_TOOLS" != "yes" ]] && echo 'FREETZ_DOWNLOAD_TOOLCHAIN=y'                       >> .config
          [[ "$COMPILE_TOOLS" == "yes" ]] && echo '# FREETZ_HOSTTOOLS_DOWNLOAD is not set'            >> .config
          [[ "$COMPILE_TOOLS" != "yes" ]] && echo 'FREETZ_HOSTTOOLS_DOWNLOAD=y'                       >> .config
          [[ "$USE_ROOTEMU" == "pseudo"   ]] && echo '# FREETZ_ROOTEMU_FAKEROOT is not set'           >> .config
          [[ "$USE_ROOTEMU" != "pseudo"   ]] && echo 'FREETZ_ROOTEMU_FAKEROOT=y'                      >> .config
          [[ "$USE_ROOTEMU" == "fakeroot" ]] && echo '# FREETZ_ROOTEMU_PSEUDO is not set'             >> .config
          [[ "$USE_ROOTEMU" != "fakeroot" ]] && echo 'FREETZ_ROOTEMU_PSEUDO=y'                        >> .config
          wget -q "${{ secrets.ACTIONS_CUSTOM }}cfg" -O cfg 2>/dev/null && mv cfg .config || rm -f cfg
          grep -q '^FREETZ_TYPE_' .config || echo "FREETZ_TYPE_$BOX=y"                                >> .config
          grep -q '^FREETZ_TYPE_FIRMWARE_' .config || echo "FREETZ_TYPE_FIRMWARE_$FOS=y"              >> .config
          echo "################################################################" && du .config && wc -l .config

      - name: addon
        run: |
          echo "################################################################"
          wget -q "${{ secrets.ACTIONS_CUSTOM }}add" -O - 2>/dev/null | tar xj 2>/dev/null && echo Done || echo Null

      - name: signature
        run: |
          mkdir -p ~/.freetz-signature/
          for x in prv pub; do wget -q "${{ secrets.ACTIONS_CUSTOM }}$x" -O ~/.freetz-signature/$x >/dev/null 2>&1 || rm -f ~/.freetz-signature/$x; done
          echo "################################################################" && ls -l ~/.freetz-signature/

      - &docker_init
        name: docker_init
        run: |
          sudo docker run -d \
            --name ${{ env.docker_NAME }} \
            -e DEBIAN_FRONTEND=noninteractive \
            -v ${GITHUB_WORKSPACE}:/mnt/freetz-ng \
            ${{ matrix.docker }} \
            sleep infinity
          sudo docker exec -i ${{ env.docker_NAME }} bash -c '\
            cd /mnt/freetz-ng && /mnt/freetz-ng/tools/prerequisites install -y
          '
          sudo docker exec -i ${{ env.docker_NAME }} bash -c '\
               groupadd freetz -o -g 1001 \
            && useradd freetz -o -s /bin/bash -d /mnt/freetz-ng -u 1001 -g 1001 \
            && usermod freetz -a -G root \
            && echo "freetz ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
            && chown -R freetz:freetz /mnt/freetz-ng \
          '

      - name: generate
        run: |
          sudo docker exec -i ${{ env.docker_NAME }} bash -c '\
          su freetz -c "cd /mnt/freetz-ng && \
          make && rm -f images/latest.image"
          '

      - name: result
        run: |
          echo "################################################################"
          ls -l images/
          sha256sum images/*

      - name: vars
        id: vars
        run: |
          LINK="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          LAST="$(ls images/*.image | sed 's,.*/,,;s,\.image$,,')"
          NAME="$(ls images/*.image | sed 's,.*/,,;s,_[0-9].*,,')"
          [ -n "$LINK" ] && echo "link=$LINK" >> $GITHUB_OUTPUT
          [ -n "$LAST" ] && echo "last=$LAST" >> $GITHUB_OUTPUT
          [ -n "$NAME" ] && echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "################################################################"
          echo "LINK=$LINK"
          echo "LAST=$LAST"
          echo "NAME=$NAME"
          test -n "$NAME"

      - name: cache_clear
        if: github.repository == 'freetz-ng/freetz-ng'
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          CACHE_KEY: ${{ env.CACHE_KEY }}
        run: |
          ASSETS="$(curl -s  -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $ACTIONS_TOKEN"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/repos/${{ github.repository }}/actions/caches")"
          ASSID="$(echo "$ASSETS" | grep -B7 "\"key\": *\"${CACHE_KEY}\"" | sed -rn 's/ *"id": *([^,]*),*/\1/p')"
          curl -sL -X DELETE -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer $ACTIONS_TOKEN"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/repos/${{ github.repository }}/actions/caches/$ASSID" && echo "Deleted ASSID=${ASSID:-null} ..." || true
      - name: cache_save
        uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            dl/*
            !dl/tools-*.tar.xz
            !dl/linux-*.tar.xz
            !dl/fw/*.zip
          key: ${{ env.CACHE_KEY }}

      - &docker_destroy
        name: docker_destroy
        if: always()
        run: |
          sudo docker stop -t 10 ${{ env.docker_NAME }} || sudo docker stop -s SIGKILL -t 10 ${{ env.docker_NAME }} || true
          sudo docker rm -f ${{ env.docker_NAME }}

  dl-toolchains:
    if: ${{ github.event.inputs.toolchains != 'no' }}
    needs: [ dockerfizieren, matrizifizieren ]
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        docker: ${{ fromJson(needs.dockerfizieren.outputs.os) }}
        fritz: ${{ fromJson(needs.matrizifizieren.outputs.matrix) }}
    name: "${{ matrix.docker }}-${{ matrix.fritz.name }}-${{ matrix.fritz.tcs }}"
    runs-on: ubuntu-latest
#   if: github.repository == 'freetz-ng/freetz-ng'

    env:
      CACHE_KEY: "${{ github.workflow }}--${{ matrix.docker }}"
      docker_NAME: "${{ github.job }}"
    steps:

      - name: args
        id: args
        run: |
          export ARGS="$(for x in ${{ matrix.fritz.tcs }}; do echo -n "$x " | sed 's/^_/FREETZ_TYPE_/'; done)"
          echo "args='$ARGS'" >> $GITHUB_OUTPUT
          echo "################################################################" && bash -c "echo ARGS='$ARGS'"
      
      - *clone

      - name: cache_load
        uses: actions/cache/restore@v4
        if: always()
        with:
          path: |
            dl/*
            !dl/linux-*.tar.xz
            !dl/*-freetz-*-shared-glibc.tar.lzma
          key: ${{ env.CACHE_KEY }}_toolchains
          restore-keys: ${{ env.CACHE_KEY }}_toolchains

      - name: version
        id: version
        run: |
          export VERSION="r$(tools/freetz_revision short)"
          [ -n "$VERSION" ] && echo "version=$VERSION" >> $GITHUB_OUTPUT || exit 1
          echo "################################################################" && bash -c "echo VERSION=$VERSION"

      - *docker_init

      - name: generate
        env:
          ACTIONS_VERSION: ${{ steps.version.outputs.version }}
        run: |
          sudo docker exec -i ${{ env.docker_NAME }} bash -c "\
          su freetz -c 'cd /mnt/freetz-ng && \
          tools/dl-toolchains_make $ACTIONS_VERSION ${{ steps.args.outputs.args }}'
          "

      - name: result
        env:
          ACTIONS_VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "################################################################"
          sudo docker exec -i ${{ env.docker_NAME }} bash -c "\
          su freetz -c 'cd /mnt/freetz-ng && \
          tools/dl-toolchains_eval $ACTIONS_VERSION all | grep -v "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"'
          "
          ls -al dl/*-shared-glibc.tar.lzma && du -sh dl/*-shared-glibc.tar.lzma

      - name: release
        uses: ncipollo/release-action@v1
        with:
          tag: dl-toolchains_${{ steps.version.outputs.version }}
          name: dl-toolchains-${{ steps.version.outputs.version }}
          body: These files are internally used!
          prerelease: true
          allowUpdates: true
          removeArtifacts: false
          artifacts: "dl/*-freetz-${{ steps.version.outputs.version }}-shared-glibc.tar.lzma"
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
          artifactErrorsFailBuild: true
          draft: true

      - *docker_destroy
