name: ufo

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  ufo:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        box: ["5690", "7270", "7490"]
    runs-on: ubuntu-latest
    
    steps:

    - shell: bash
      run: echo DATE=$(date +%F_%R) >> $GITHUB_ENV

    - uses: actions/cache@v4
      with:
        path: |
          ~/
          ./
        key: cache-${{ github.ref_name }}-${{ matrix.box }}-${{ env.DATE }}
        restore-keys: cache-${{ github.ref_name }}-${{ matrix.box }}

    - uses: actions/checkout@v6
      with:
        clean: false

    - run: |
        tools/prerequisites install
        cp config-${{ matrix.box }} .config
        rm images/* || $(exit 0)
        touch -d 2020-01-01 make/kernel/configs/freetz/config-ur8-7270_06.05
        # make kernel-dirclean

    - run: |
        make
        grep -v '#  freetz-ng ' .config > config-${{ matrix.box }}

    - uses: EndBug/add-and-commit@v9
      with:
        push: false
        
    - run: git pull --rebase && git push

    - uses: actions/upload-artifact@v4
      with:
        name: images-${{ matrix.box }}
        path: images
        retention-days: 2
